# Generated by Django 4.2 on 2024-06-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_price"),
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="flower",
        ),
        migrations.AddField(
            model_name="wishlist",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Flower",
        ),
    ]
