# Generated by Django 4.2 on 2024-07-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0002_remove_wishlist_flower_wishlist_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="quantity",
        ),
    ]
