# Generated by Django 4.2 on 2024-07-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0003_remove_wishlist_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
