# Generated by Django 4.2 on 2024-06-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="author",
        ),
    ]
