# Generated by Django 4.2 on 2024-05-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_price_l_product_price_m_product_price_s"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=6, null=True
            ),
        ),
    ]
